package com.deepdark.lab2.utils

const val COAL_LOWER_HEATING_VALUE = 20.47
const val COAL_LIGHT_ASH_CONTENT = 0.8
const val COAL_ASH_MASS_CONTENT = 25.2
const val COAL_COMBUSTIBLE_MASS_CONTENT = 1.5
const val COAL_CLEANING_EFFICIENCY = 0.985

const val FUEL_OIL_LOWER_HEATING_VALUE = 40.4
const val FUEL_OIL_LIGHT_ASH_CONTENT = 1.0
const val FUEL_ASH_MASS_CONTENT = 0.15
const val FUEL_OIL_COMPONENT_PERCENTAGE_G = 0.0
const val FUEL_OIL_CLEANING_EFFICIENCY = 0.985